environment:

  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install pandas"
  - "%PYTHON%\\python.exe -m pip install pytest"

build: off

test_script:
  - "%PYTHON%/Scripts/py.test"
  - "%PYTHON%\\python.exe hydrologyChallenge_test.py test"

